import { useState } from "react";

export function BulkClassEditor({ rules, isBusy, onApply }) {
  const [form, setForm] = useState({ templateId: "", startDate: "", endDate: "", className: "", time: "", instructor: "", inPersonCapacity: "", onlineCapacity: "", updateZoom: false, zoomUrl: "" });
  const [error, setError] = useState("");
  const update = (field, value) => { setForm((current) => ({ ...current, [field]: value })); setError(""); };
  function submit(event) { event.preventDefault(); if (!form.startDate || !form.endDate || form.endDate < form.startDate) return setError("Choose a valid start and end date."); if (!form.className && !form.time && !form.instructor && form.inPersonCapacity === "" && form.onlineCapacity === "" && !form.updateZoom) return setError("Enter at least one change."); if (form.updateZoom && !form.zoomUrl.trim()) return setError("Paste the new Zoom link."); if (!window.confirm("Apply these changes to every matching future class? Booked clients receive an email when the time changes.")) return; onApply({ ...form, zoomUrl: form.zoomUrl.trim() }); }
  return <form className="admin-bulk-editor" onSubmit={submit}><div className="admin-bulk-editor__head"><div><p className="eyebrow">Bulk update</p><h3>Update existing future classes</h3></div><p>Leave any field empty to keep its current value. Capacity cannot be lower than confirmed bookings.</p></div><label>Apply to<select value={form.templateId} onChange={(event) => update("templateId", event.target.value)}><option value="">All class types</option>{rules.map((rule) => <option key={rule.templateId} value={rule.templateId}>{rule.className} — {rule.day} · {rule.time}</option>)}</select></label><label>From date<input type="date" value={form.startDate} onChange={(event) => update("startDate", event.target.value)} required /></label><label>To date<input type="date" value={form.endDate} onChange={(event) => update("endDate", event.target.value)} required /></label><label>New class name <small>Optional</small><input value={form.className} onChange={(event) => update("className", event.target.value)} placeholder="Keep current" /></label><label>New time <small>Optional</small><input value={form.time} onChange={(event) => update("time", event.target.value)} placeholder="Keep current" /></label><label>New instructor <small>Optional</small><input value={form.instructor} onChange={(event) => update("instructor", event.target.value)} placeholder="Keep current" /></label><label>In-person capacity <small>Optional</small><input type="number" min="0" value={form.inPersonCapacity} onChange={(event) => update("inPersonCapacity", event.target.value)} placeholder="Keep current" /></label><label>Online capacity <small>Optional</small><input type="number" min="0" value={form.onlineCapacity} onChange={(event) => update("onlineCapacity", event.target.value)} placeholder="Keep current" /></label><label className="admin-bulk-editor__zoom-toggle"><input type="checkbox" checked={form.updateZoom} onChange={(event) => update("updateZoom", event.target.checked)} /> Replace Zoom link</label>{form.updateZoom && <label>New Zoom link<input type="url" value={form.zoomUrl} onChange={(event) => update("zoomUrl", event.target.value)} required /></label>}{error && <p className="admin-bulk-editor__error" role="alert">{error}</p>}<button className="button gold" type="submit" disabled={isBusy}>Apply Bulk Changes</button></form>;
}
