import { useState } from "react";
import { TemplateEditor } from "./TemplateEditor.jsx";

const DAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
const emptyRule = { className: "", day: "Monday", time: "", instructor: "Sherazade", inPersonCapacity: 10, onlineCapacity: 0, zoomUrl: "" };
const emptyMany = { className: "", startDate: "", endDate: "", time: "", instructor: "Sherazade", inPersonCapacity: 10, onlineCapacity: 0, zoomUrl: "", saveRule: false, days: [] };

export function ScheduleManager({ templates, isBusy, onUpdate, onCreate, onDelete, onGenerate, onDuplicate, onCreateMany, onBulkRemove }) {
  const rules = templates.filter((item) => !item.isOneTime);
  const [rule, setRule] = useState(emptyRule);
  const [range, setRange] = useState({ startDate: "", endDate: "", templateIds: [] });
  const [duplicate, setDuplicate] = useState({ sourceDate: "", startDate: "", endDate: "" });
  const [many, setMany] = useState(emptyMany);
  const [remove, setRemove] = useState({ templateId: "", startDate: "", endDate: "" });
  const toggle = (list, value) => list.includes(value) ? list.filter((item) => item !== value) : [...list, value];
  return <section className="admin-panel" aria-labelledby="schedule-admin-title"><div className="admin-panel__head"><div><p className="eyebrow">Plan your calendar</p><h2 id="schedule-admin-title">Schedule & Future Classes</h2></div></div><p className="admin-help">Create future dates only for the period you choose. A weekly schedule rule is simply your repeating class plan.</p>
    <section className="admin-workspace"><h3>Weekly schedule rules</h3><p>Add or edit the repeating class plans Shera normally teaches each week.</p><form className="admin-template-card admin-template-card--new" onSubmit={(event) => { event.preventDefault(); onCreate(rule); setRule(emptyRule); }}><label>Class name<input value={rule.className} onChange={(event) => setRule({ ...rule, className: event.target.value })} required /></label><label>Day<select value={rule.day} onChange={(event) => setRule({ ...rule, day: event.target.value })}>{DAYS.map((day) => <option key={day}>{day}</option>)}</select></label><label>Time<input value={rule.time} onChange={(event) => setRule({ ...rule, time: event.target.value })} placeholder="6:00 PM – 7:00 PM" required /></label><label>Instructor<input value={rule.instructor} onChange={(event) => setRule({ ...rule, instructor: event.target.value })} required /></label><label>In-person capacity<input type="number" min="0" value={rule.inPersonCapacity} onChange={(event) => setRule({ ...rule, inPersonCapacity: event.target.value })} required /></label><label>Online capacity<input type="number" min="0" value={rule.onlineCapacity} onChange={(event) => setRule({ ...rule, onlineCapacity: event.target.value })} required /></label><label>Zoom link<input type="url" value={rule.zoomUrl} onChange={(event) => setRule({ ...rule, zoomUrl: event.target.value })} /></label><button className="button gold" disabled={isBusy}>Add weekly rule</button></form><div className="admin-template-list">{rules.map((item) => <div className="admin-rule" key={item.templateId}><TemplateEditor template={item} isBusy={isBusy} onUpdate={onUpdate} /><button className="admin-danger" type="button" disabled={isBusy} onClick={() => onDelete(item.templateId)}>Delete rule</button></div>)}</div></section>
    <section className="admin-workspace"><h3>Create future classes</h3><p>Choose the rules and exact date range. Only missing dates are created.</p><form className="admin-range-form" onSubmit={(event) => { event.preventDefault(); onGenerate(range); }}><label>Start date<input type="date" value={range.startDate} onChange={(event) => setRange({ ...range, startDate: event.target.value })} required /></label><label>End date<input type="date" value={range.endDate} onChange={(event) => setRange({ ...range, endDate: event.target.value })} required /></label><fieldset><legend>Weekly rules <small>Leave all unselected for every rule</small></legend>{rules.map((item) => <label className="admin-check" key={item.templateId}><input type="checkbox" checked={range.templateIds.includes(item.templateId)} onChange={() => setRange({ ...range, templateIds: toggle(range.templateIds, item.templateId) })} />{item.className} — {item.day}</label>)}</fieldset><button className="button gold" disabled={isBusy}>Create missing dates</button></form></section>
    <section className="admin-workspace"><h3>Duplicate an existing week</h3><p>Copy every class from one existing week into future weeks. Bookings are never copied.</p><form className="admin-range-form" onSubmit={(event) => { event.preventDefault(); onDuplicate(duplicate); }}><label>Any date in source week<input type="date" value={duplicate.sourceDate} onChange={(event) => setDuplicate({ ...duplicate, sourceDate: event.target.value })} required /></label><label>Copy from date<input type="date" value={duplicate.startDate} onChange={(event) => setDuplicate({ ...duplicate, startDate: event.target.value })} required /></label><label>Copy through date<input type="date" value={duplicate.endDate} onChange={(event) => setDuplicate({ ...duplicate, endDate: event.target.value })} required /></label><button className="button gold" disabled={isBusy}>Duplicate week</button></form></section>
    <section className="admin-workspace"><h3>Create many classes</h3><p>Use this for a new class running on selected days within a date range.</p><form className="admin-range-form admin-range-form--many" onSubmit={(event) => { event.preventDefault(); onCreateMany(many); }}><label>Class name<input value={many.className} onChange={(event) => setMany({ ...many, className: event.target.value })} required /></label><label>Start date<input type="date" value={many.startDate} onChange={(event) => setMany({ ...many, startDate: event.target.value })} required /></label><label>End date<input type="date" value={many.endDate} onChange={(event) => setMany({ ...many, endDate: event.target.value })} required /></label><label>Time<input value={many.time} onChange={(event) => setMany({ ...many, time: event.target.value })} required /></label><label>Instructor<input value={many.instructor} onChange={(event) => setMany({ ...many, instructor: event.target.value })} required /></label><label>In-person capacity<input type="number" min="0" value={many.inPersonCapacity} onChange={(event) => setMany({ ...many, inPersonCapacity: event.target.value })} required /></label><label>Online capacity<input type="number" min="0" value={many.onlineCapacity} onChange={(event) => setMany({ ...many, onlineCapacity: event.target.value })} required /></label><label>Zoom link<input type="url" value={many.zoomUrl} onChange={(event) => setMany({ ...many, zoomUrl: event.target.value })} /></label><fieldset><legend>Repeat on</legend>{DAYS.map((day) => <label className="admin-check" key={day}><input type="checkbox" checked={many.days.includes(day)} onChange={() => setMany({ ...many, days: toggle(many.days, day) })} />{day}</label>)}</fieldset><label className="admin-check"><input type="checkbox" checked={many.saveRule} onChange={(event) => setMany({ ...many, saveRule: event.target.checked })} />Also add as a weekly schedule rule</label><button className="button gold" disabled={isBusy}>Create many classes</button></form></section>
    <section className="admin-workspace admin-workspace--danger"><h3>Remove future classes in bulk</h3><p>Empty classes are deleted. Classes with bookings are cancelled, clients are refunded, and clients are emailed.</p><form className="admin-range-form" onSubmit={(event) => { event.preventDefault(); onBulkRemove(remove); }}><label>Class rule <small>Optional</small><select value={remove.templateId} onChange={(event) => setRemove({ ...remove, templateId: event.target.value })}><option value="">All class types</option>{rules.map((item) => <option key={item.templateId} value={item.templateId}>{item.className} — {item.day}</option>)}</select></label><label>Start date<input type="date" value={remove.startDate} onChange={(event) => setRemove({ ...remove, startDate: event.target.value })} required /></label><label>End date<input type="date" value={remove.endDate} onChange={(event) => setRemove({ ...remove, endDate: event.target.value })} required /></label><button className="admin-danger" disabled={isBusy}>Remove selected classes</button></form></section>
  </section>;
}
